// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Cities struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CityCode  string    `json:"city_code"`
	CreatedAt time.Time `json:"created_at"`
	IsActive  bool      `json:"is_active"`
}

type Employees struct {
	ID         int64          `json:"id"`
	FirstName  string         `json:"first_name"`
	LastName   string         `json:"last_name"`
	MiddleName sql.NullString `json:"middle_name"`
	Phone      string         `json:"phone"`
	CreatedAt  time.Time      `json:"created_at"`
	CityID     int64          `json:"city_id"`
}
